### PR TITLE
Add a netstandard1.4 version

### PR DESCRIPTION
**Pull request by hansmbakker**
Add a netstandard1.4 version so that we can use this with .Net Core

### CODE REVIEW

**Comment by brockallen** [comment]
that's what this project is: https://github.com/IdentityModel/IdentityModel2

**Comment by hansmbakker** [comment]
@brockallen that's really a shame - the difference between those two repos is very unclear (e.g. no clear difference in the readme or title) and in general there are so many repos in the IdentityModel that it is difficult to pick the right one..

**Comment by leastprivilege** [comment]
then ask...

**Comment by weitzhandler** [comment]
@wind-rider 
I wouldn't want it to be netstandard. I at least IdentityModel1 should be kept non-netstandard, so to support PCLs and others.

**Pull request closed without merging**
