### PR TITLE
Added DiscoveryClient.

### PR DESCRIPTION
**Pull request by weitzhandler**
@leastprivilege 

Regarding [your comment](https://github.com/IdentityModel/IdentityModel2/issues/21#issuecomment-301687836), this PR adds DiscoveryClient.
Thrived to make the least changes possible, and leave the existing code intact.

### CODE REVIEW

**Comment by leastprivilege** [comment]
Thanks - 

2 things

* please use the dev branch
* remove the .VS folder (maybe needs updating the ignore file)

**Comment by weitzhandler** [comment]
@leastprivilege is there a way to migrate my changes from master to dev since I initially started from master or I'm gonna have to redo everything?

**Comment by hansmbakker** [comment]
You can use `git rebase` locally with the proper parameters to make your commits 'originate' from dev, then force push this to your repo on github.

**Comment by weitzhandler** [comment]
@leastprivilege 
Issues addressed #67

**Pull request closed without merging**
