### PR TITLE
implemented enhancement to AuthorizeRequest that allow relative Urls

### PR DESCRIPTION
**Pull request by netsrotr**
see https://github.com/IdentityModel/IdentityModel/issues/56

### CODE REVIEW

**Comment by leastprivilege** [comment]
You want that in v1 ? Or should we make that change in v2?

**Comment by netsrotr** [comment]
It should go into the version with .NET 4.5 support or both - it is small enough :-)

**Comment by leastprivilege** [comment]
I am not planning to do non-security related updates to v1 anymore. Does v2 work for you?

**Comment by netsrotr** [comment]
Why not? Not all users of the libs are/can always working with the newest .NET versions. But it is your decision, within Silverlight I just also cannot use v1 :-(

**Comment by leastprivilege** [comment]
v2 supports .NET 4.5 - did you actually try it?

**Comment by leastprivilege** [comment]
merged into v2. thanks

**Pull request closed without merging**
